---
- name: upgrade all packages
  become: true
  apt:
    upgrade: "yes"

- name: where am I
  shell: |
    ls
    pwd
  register: print_result

- name: print message
  debug:
    msg: "{{ print_result.stdout_lines }}"

- name: create backend directory
  shell: |
    mkdir -p backend

- name: Unarchive files
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: backend

- name: Start backend
  shell: |
    npm install 
    pm2 stop default
    pm2 start npm -- start
