---
- name: upgrade all packages
  become: true
  apt:
    upgrade: "yes"

- name: where am I
  shell: |
    ls
    pwd

- name: Unarchive files
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: backend

- name: Start backend
  shell: |
    npm install 
    pm2 stop default
    pm2 start npm -- start
